### ISSUE TITLE
The example from the README does not work

### ISSUE THREAD

**Issue by hdralexandru** [ep2p/kademlia-netty#5]
I've tried to run the `Example` test-file, however it fails. Even though node2 contains key `K`, the result returned is `null`

This is what the console prints:

```
Bootstrapped? true
STORED
2
FAILED
null
```

**Comment by sepgh** [comment]
Thank you for bringing this to my attention.

Is it possible to post the full code you wrote here?

I'll make new sample ASAP and test again.

**Comment by sepgh** [comment]
According to our conversation on Discord, the problem was with not passing valid `RoutingTable` and `ID` to second node. Passing valid ones will fix the problem.

Closing this issue.
