### ISSUE TITLE
How you handle Kademlia attacks?

### ISSUE THREAD

**Issue by l16h7n1n6s** [ep2p/kademlia-netty#6]
I list some of the well known attacks that can be use in kademlia P2P network

1. Sybil Attacks — where a user generates an extreme number of arbitrary identities (NodeIDs) to flood the network.
2. Eclipse Attacks — where an attacker attempts to isolate a node or set of nodes in the network graph by ensuring that all outbound connections reach malicious nodes

Any explanation of how can we prevent this cases ? will it  be hard to implement or give some ideas about how to implement?

**Comment by sepgh** [comment]
So far this repository only handles serialization and networking layer, and does not care about how node IDs are generated, verified and how complex messages are sent over the network, therefor dealing with those attacks requires the consumer application to implement it.

I strongly suggest this document:
https://medium.com/coinmonks/a-brief-overview-of-kademlia-and-its-use-in-various-decentralized-platforms-da08a7f72b8f
